module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#0b1c30',
        'tertiary-fixed': '#c4e7ff',
        'primary-fixed': '#dde1ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'error-container': '#ffdad6',
        'surface-container-high': '#dce9ff',
        'on-tertiary-container': '#caeaff',
        'tertiary-fixed-dim': '#7bd0ff',
        'tertiary-container': '#006e95',
        'surface-container-highest': '#d3e4fe',
        'surface': '#f8f9ff',
        'on-surface': '#0b1c30',
        'on-tertiary-fixed': '#001e2c',
        'surface-tint': '#004ced',
        'on-surface-variant': '#434656',
        'surface-dim': '#cbdbf5',
        'primary-container': '#0052ff',
        'secondary-container': '#dae2fd',
        'inverse-surface': '#213145',
        'on-primary-fixed-variant': '#0038b6',
        'on-secondary-container': '#5c647a',
        'secondary': '#565e74',
        'on-tertiary-fixed-variant': '#004c69',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#001452',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#3f465c',
        'error': '#ba1a1a',
        'outline': '#737688',
        'surface-variant': '#d3e4fe',
        'tertiary': '#005474',
        'inverse-primary': '#b7c4ff',
        'inverse-on-surface': '#eaf1ff',
        'primary': '#003ec7',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#b7c4ff',
        'on-secondary-fixed': '#131b2e',
        'secondary-fixed': '#dae2fd',
        'background': '#f8f9ff',
        'on-primary-container': '#dfe3ff',
        'outline-variant': '#c3c5d9',
        'secondary-fixed-dim': '#bec6e0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        margin: '32px',
        unit: '8px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-sm': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' }],
        'display-md': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '0', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};